joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 250

egm_state_controller:
  type         : abb_egm_state_controller/EGMStateController
  publish_rate : 250


position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1 
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
